
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT'
export const GET_PROJECT_CATEGOTY = 'GET_PROJECT_CATEGOTY'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const PROJECT_DETAIL = 'PROJECT_DETAIL'
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

export const GET_LIST_MEMBER = 'GET_LIST_MEMBER'
export const USER_SEARCHED = 'USER_SEARCHED'

export const SEARCH_USER = 'SEARCH_USER'